try:
    1+1
except ValueError:
    raise 
finally:
    2 + 2